<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>fransTest</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-09-25T15:32:05</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b30efe2a-090f-4cc8-9626-a45392dcfcdc</testSuiteGuid>
   <testCaseLink>
      <guid>014e25e5-3a78-49ea-87e0-45a9d990a1ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Test/Test1</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>eee5b6d1-d26d-44e7-bf22-53745cfcbab1</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/QA2URLS</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>eee5b6d1-d26d-44e7-bf22-53745cfcbab1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>QA2URLS </value>
         <variableId>1727e7ff-cc79-4508-a258-69a9f027e16d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>27fef074-cbb6-49c3-9115-befebf12219e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Test/Test2</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f50ca484-20a0-44a9-b73a-168d93aa9503</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/New Test Data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>f50ca484-20a0-44a9-b73a-168d93aa9503</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>QA2URLS </value>
         <variableId>e173ed44-db02-4cee-af9a-c5fdcbe1a6d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f50ca484-20a0-44a9-b73a-168d93aa9503</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UserNames</value>
         <variableId>a3d5c4ab-d5a6-4582-b3af-5deae057b382</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f50ca484-20a0-44a9-b73a-168d93aa9503</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UserPasswords</value>
         <variableId>a1d8aebc-132e-461d-a413-8fe2b93baf06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f50ca484-20a0-44a9-b73a-168d93aa9503</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>SiteName</value>
         <variableId>77cfda55-43d4-432b-9a2a-ac9331a7d418</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0b45db01-0f4a-4e2d-a3af-c6fd9c34d901</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Test/Test3</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>86fe5b93-967a-4848-b77d-3dd420065072</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/ProdData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>86fe5b93-967a-4848-b77d-3dd420065072</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ProdNumber</value>
         <variableId>6c634a81-236c-46a6-872f-f92c0c3e1cb7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>86fe5b93-967a-4848-b77d-3dd420065072</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ProdName</value>
         <variableId>6ac8eaec-ac1f-402b-9665-36211ac6ec3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>605d8d55-d132-4909-b464-54eb3b3fe836</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef73bf47-cead-4050-a774-8464d205c95c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54f68b83-249f-4fcd-9a64-3600a5a7c87e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d201c1e-5327-43fc-adcc-a6aba814500c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Test/Test4</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ea706731-83d0-401b-877f-c9bb46e6a472</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/QA2URLS</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>ea706731-83d0-401b-877f-c9bb46e6a472</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>QA2URLS </value>
         <variableId>3ab53bc0-b122-40c8-8b8e-638cfe15ccf3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ea706731-83d0-401b-877f-c9bb46e6a472</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UserNames</value>
         <variableId>2cb4d89a-f382-4be7-be3d-60b502636ac1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ea706731-83d0-401b-877f-c9bb46e6a472</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UserPasswords</value>
         <variableId>2c6578ea-cf8e-4fa5-9686-008f0e5d61d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ea706731-83d0-401b-877f-c9bb46e6a472</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>e9ed7271-9288-44c9-b226-d01bdc3629c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>31b27166-2b16-4a4e-bf4f-7ba3a639894a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Products/VerifyPics</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7590712b-0576-4ab7-b99b-af0b5bf41d89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>638f3881-04b0-42df-8ae8-19deb4a3eeba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9426e35a-b9bc-4c3a-8275-0da3f533ff94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc8c89f2-ef26-4d0c-adb5-7ac2b47114fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11e7d678-e529-42f1-a04d-882c30b12df3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c8419d0b-35a5-49ad-9caa-1a1db98025fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/PLPTest</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>2c37620d-5955-4f97-90f9-96087fa73413</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Products V8</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f9943aba-b11f-4a6a-a0b3-5e3b662b3804</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/ProdData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>f9943aba-b11f-4a6a-a0b3-5e3b662b3804</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ProdNumber</value>
         <variableId>8bfc2d52-b417-4d73-a19c-7f553f925c17</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f9943aba-b11f-4a6a-a0b3-5e3b662b3804</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ProdName</value>
         <variableId>e07fcb06-1542-4d5a-9981-5d935f1af776</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6f68f25-b9dc-4561-8712-098af158a939</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e88d11e6-60c6-4b1f-b33c-466ad6a0c204</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96b17fb4-642a-490f-bcbf-6ca66e82935b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d235553-85c0-434f-9eaf-abc087bcfd97</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Products/Products Cooper</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>24cf8e93-9d26-4a6a-82ee-d3b305ad4c5d</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/cooper</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcc4dc6a-a961-435b-8cbe-413305e1b770</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c6753d7-e016-4e2e-a62c-338877da0ec2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95d35faf-b46c-45fc-9948-73135d2dac06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4160cae4-b46e-4877-989c-d1c3190443a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5986a56a-3d68-4524-b693-5ce90c501e22</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Product images src</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9dc7b560-5b15-4bfb-8de0-0ac27380bd0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a2dc43e-0ff2-47e2-9cdf-8fc84e0ed1fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6aebdc5-5d77-4823-98ef-999ba62c3a0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f5693da-fedd-4b39-b4f0-f454916b3216</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba87ebca-4c88-4bd7-b351-c5155026d961</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d927d979-e16a-46f9-b627-7a296b10bcf5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Products/Products Viking</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30add107-e35b-4fe0-b52c-fb138f51d6aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>697e27a3-1695-4224-934b-743aa4890667</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbdcce10-7fe0-487c-aa2d-2088cbb7ff2e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>417ccf33-3f9d-4057-9a28-1bfae6323fef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41a17748-f3eb-4f1c-b151-0d1640a57a0e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2263ff5a-fb12-471e-bc74-a063ccdf2274</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>82090ef5-4aa8-4292-a25b-5828bbdd768f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Products/Products IRBY</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c277fc2-66ba-47dd-b73f-8d378996fefe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9471ceb4-6b99-4f48-a4af-b5e098cdf064</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c40b5442-b61a-43ad-9f17-bbcd90e4e625</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea8af22f-9029-465b-a36d-7a48d285fbaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b09772d-96a2-4b09-9d14-04acfcb6ceb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8b0cfe9-cc75-436f-aa58-2f08f52adb9f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac764e8d-b6bf-48df-a44a-6e08e7c18b99</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Products/Products Crawford</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c230b61-1098-48a3-89e8-9f5732ee3bd2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd577952-ea7f-4759-af2e-9e3ec6291604</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26a5f488-c654-41e3-86d9-ca27b76f465e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab548184-7347-4e6e-a323-31fec969410e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d2e2b72-a844-4528-a326-e190df960d7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Products/Products Capital</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a95c66f-a20f-48fd-b2be-9744aac1bb19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49e9cf64-a220-4d0d-9a77-88e8802ca069</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>098d87f9-1436-4257-a928-4fec9c1b50a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21131d7a-fe38-441d-ae57-d567d360e6ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71e0d7e3-6a18-465b-bb53-ce0e914667d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b3a09f1-c9cd-4b5e-ab67-5a4c1b15e356</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
