<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Products3</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-10-03T12:21:17</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>a5d3f578-58a5-4c63-904b-1bc1a6ee7e81</testSuiteGuid>
   <testCaseLink>
      <guid>d28e3f26-ead6-4c11-bfd2-796369fc38f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Products/Products Capital</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a95c66f-a20f-48fd-b2be-9744aac1bb19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49e9cf64-a220-4d0d-9a77-88e8802ca069</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>098d87f9-1436-4257-a928-4fec9c1b50a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21131d7a-fe38-441d-ae57-d567d360e6ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71e0d7e3-6a18-465b-bb53-ce0e914667d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b3a09f1-c9cd-4b5e-ab67-5a4c1b15e356</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d184d29-8012-4846-af65-5e0ba8aeb635</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Products/Products Cooper</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcc4dc6a-a961-435b-8cbe-413305e1b770</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c6753d7-e016-4e2e-a62c-338877da0ec2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95d35faf-b46c-45fc-9948-73135d2dac06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4160cae4-b46e-4877-989c-d1c3190443a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>918d92f0-ec53-4eca-ae54-701fdc6c5508</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Products/Products Crawford</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c230b61-1098-48a3-89e8-9f5732ee3bd2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd577952-ea7f-4759-af2e-9e3ec6291604</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26a5f488-c654-41e3-86d9-ca27b76f465e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab548184-7347-4e6e-a323-31fec969410e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d29692cf-7b0a-49a5-8038-ba0530f0ffa5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Products/Products IRBY</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c277fc2-66ba-47dd-b73f-8d378996fefe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9471ceb4-6b99-4f48-a4af-b5e098cdf064</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c40b5442-b61a-43ad-9f17-bbcd90e4e625</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea8af22f-9029-465b-a36d-7a48d285fbaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b09772d-96a2-4b09-9d14-04acfcb6ceb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8b0cfe9-cc75-436f-aa58-2f08f52adb9f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>afb5bb42-e500-4a33-8da0-ca0b12ad3619</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Products/Products Viking</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30add107-e35b-4fe0-b52c-fb138f51d6aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>697e27a3-1695-4224-934b-743aa4890667</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbdcce10-7fe0-487c-aa2d-2088cbb7ff2e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>417ccf33-3f9d-4057-9a28-1bfae6323fef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41a17748-f3eb-4f1c-b151-0d1640a57a0e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2263ff5a-fb12-471e-bc74-a063ccdf2274</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>96687b2a-45b0-46cf-90e9-78a46f83dab7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Images/Capital Image</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e14f93f6-9d17-4889-b1b1-5ca3894c616a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c9a8419-ac75-4669-9633-3b36d50223ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d6ad03d-6498-4177-8c72-826632ef8764</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0987d11a-54b9-424e-a01e-6a9ba9a94d87</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>59ce75e4-c44f-433e-be69-ef530499367d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Images/Cooper Image</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84556b09-f1b2-44ce-a5a6-cb35cb22b7ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbda1046-797d-4b07-adbc-d8f15e96784f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52ba6c84-158f-4a21-8bab-bce691b573c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>508285e6-df15-4efc-a775-c494dfa40447</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9f4b548e-9e95-4f76-aafd-33aa9c6fc3d7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Images/Crawford Image</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c80649a-cbe6-4b9b-9cd6-ae97dde51561</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9c875f4-b227-412c-82ff-ae14c5ef38cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de1e7cc6-bb38-4b6d-a5a4-0cee92cec235</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc940956-a3d0-4b96-bf3b-e63c4d91a342</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f6dc6f83-506b-462e-a450-2e8bc9389d0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Images/IRBY Image</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5dda4c5e-e812-40b2-a072-d625388b5895</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b05a1c7-ccc7-491d-bef2-68fdfc831648</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24bfab5d-d196-4744-87fa-c4824dd4576a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0035960-8cf7-4203-ae81-559d63864e0d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>38bff47b-7343-4718-9a4a-d7dfbcdcfd9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Images/Viking Image</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5885444-9a4d-4993-bab9-0084dd28539c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7895a21f-3595-4928-bc64-f2d4f9803f1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0df4f000-5fac-4227-a5b6-8c34adab4aa6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81195346-6efe-4047-ba83-a395fbf8e014</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
