<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>V7</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-09-28T10:17:38</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b5db394c-aa83-4c66-88e8-a332353f3235</testSuiteGuid>
   <testCaseLink>
      <guid>653bf5b9-d3cc-4039-95fc-79ebe0b752b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Products V7</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>604652b9-9a1e-4443-a34e-86500838ea3b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd89f378-c24d-42d1-a6f6-af0c0e99a7ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2c1c597-8fae-4261-980e-d4f9f47e9f98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e5c5cbb-5a2c-435a-870e-2870367f62e4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
