<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add Address</name>
   <tag></tag>
   <elementGuidId>bd0f6bbd-2358-4ec1-934e-d9c8a44a5933</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button_text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Add Address
          </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addnew_content_footer&quot;)/div[@id=&quot;WC_AjaxAddressBookForm_div_16a&quot;]/div[@id=&quot;WC_AjaxAddressBookForm_div_16b&quot;]/a[@id=&quot;WC_AjaxAddressBookForm_links_4a&quot;]/div[@class=&quot;button_text&quot;]</value>
   </webElementProperties>
</WebElementEntity>
