<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img01</name>
   <tag></tag>
   <elementGuidId>0109d654-24db-465d-896e-92710d9a1634</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[7]/div[3]/div/div[3]/div[1]/div/div/div/div/div/ul/li/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://qa2-www.vikingelectric.com//wcsstore/SoneparUSB2BSAS/images/US/ProductImages/199315-ProductImage500-SUSA_199315.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Pass &amp;amp; Seymour 2601-GRY 15 Amp 120/277 VAC 1-Pole Gray Polycarbonate Screw Mounting Rocker Decorator Switch</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[7]/div[3]/div/div[3]/div[1]/div/div/div/div/div/ul/li/img</value>
   </webElementProperties>
</WebElementEntity>
