<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_0</name>
   <tag></tag>
   <elementGuidId>2786f0b4-4214-4053-98e6-cb12fab8aae4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;widget_minishopcart&quot;)[count(. | //*[@onclick = concat('javascript:toggleMiniShopCartDropDown(' , &quot;'&quot; , 'widget_minishopcart' , &quot;'&quot; , ',' , &quot;'&quot; , 'quick_cart_container' , &quot;'&quot; , ',' , &quot;'&quot; , 'orderItemsList' , &quot;'&quot; , ');') and @aria-label = 'Cart']) = count(//*[@onclick = concat('javascript:toggleMiniShopCartDropDown(' , &quot;'&quot; , 'widget_minishopcart' , &quot;'&quot; , ',' , &quot;'&quot; , 'quick_cart_container' , &quot;'&quot; , ',' , &quot;'&quot; , 'orderItemsList' , &quot;'&quot; , ');') and @aria-label = 'Cart'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>widget_minishopcart</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:toggleMiniShopCartDropDown('widget_minishopcart','quick_cart_container','orderItemsList');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Cart</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	
		0
	
	
	
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;widget_minishopcart&quot;)</value>
   </webElementProperties>
</WebElementEntity>
