<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_My Carts</name>
   <tag></tag>
   <elementGuidId>00b86c01-5296-4c5a-a648-28202601f9b7</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://qa2-www.irby.com/shop/ListOrdersDisplayView?myAcctMain=1&amp;page=savedorder&amp;catalogId=3074457345616676718&amp;langId=-1&amp;storeId=715838041</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WC_MyAccountSidebarDisplayf_links_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					                My Carts
					              </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myAccountLinks&quot;)/ul[1]/li[13]/a[@id=&quot;WC_MyAccountSidebarDisplayf_links_0&quot;]</value>
   </webElementProperties>
</WebElementEntity>
